### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by harry-ma-qiang** [harry-ma-qiang/epg-info#1]
- [ ] Get contact with CIK project manager
- [ ] Get contact with SZ project manager
- [ ] Understand the requirement
- [ ] **Breakdown the sub-tasks**
- [ ] Setup staging ENV on your local machine
- [ ] Setup testing ENV on CIK
- [ ] UAT
